name = "thekiwistore"
pages_build_output_dir = "."
compatibility_date = "2026-10-09"

[[d1_databases]]
binding = "DB"
database_name = "thekiwistore-orders"
database_id = "e1cb1f97-7099-4aed-95fa-be4830a1652d"
